return {
	"williamboman/mason.nvim",
	event = "VeryLazy",
	opts = {
		ensure_installed = {
			"ada-language-server",
			"lua-language-server",
			"clangd",
			"clang-format",
			"asm-lsp",
			"vue-language-server",
			"bash-language-server",
			"shfmt",
			"css-lsp",
			"html-lsp",
			"eslint-lsp",
			"json-lsp",
			"pyright",
			"debugpy",
			"ruff-lsp",
			"rust-analyzer",
			"taplo",
			"gopls",
			"goimports",
			"marksman",
			"markdownlint",
			"ltex-ls",
			"neocmakelsp",
			"kotlin-language-server",
			"intelephense",
		},
	},
}
