require("startup").setup ({
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
			"⣿⣿⣿⣇⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⡿⣿⣿⣿⣭⣿⣿⣿⣿⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣿⣿⣾⣽⣿⣿⣿⣿⢿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⢿⣷⣾⣿⣝⣿⢿⣿⣷⣌⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠈⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣿⣿⣿⣞⡿⣻⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⠛⠛⠛⠁⠀⠙⠋⠙⠿⢿⣿⡿⢿⠾⢿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣿⣿⣿⣿⡿⣬⡊⠛⢻⣿⣿⠛⠛⠀⠀⠀⠀⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠈⠂⠀⠀⠁⠿⣿⣿⣿⣿⣿⣿⡿⠀⠀⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣿⣿⣿⣿⣾⣿⢛⣴⠖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠤⠠⠀⡀⢀⣿⣿⣿⣿⣿⣿⣽⡄⢰⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣿⣿⣯⣧⣿⣯⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⣾⣿⣿⣿⣿⣿⣾⠀⠘⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣿⣿⣿⠻⠗⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⣿⣿⣿⡇⢿⡀⣿⣿⣿⣿⣿⣿⣿",
			"⣿⣿⣟⢻⡟⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⠃⠀⣿⣿⣿⣿⣿⣿⣿⣿",
			"⣿⣯⣿⢸⠇⠀⠀⠀⠀⢠⠀⠣⢿⣧⠆⠄⢿⣿⠀⠀⠈⢢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⢻⣿⣿⣿⣿⣟⢿⣿",
			"⣿⣿⣿⡌⠀⠀⠀⠀⠀⠀⠀⡀⠁⠙⠉⠀⠂⠀⠀⠀⠀⠀⢫⣴⣦⣀⡀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿",
			"⣯⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⣿⡀⠀⠀⠀⠀⠈⢦⡀⠀⠀⠘⣿⣿⠿⠋⠀⠀⠠⣀⡀⡀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⣿⣿⣿⣿⡿⡿⢿",
			"⣿⣿⣏⠇⠀⠀⠀⠀⠀⠀⠀⢿⣿⡄⠀⠀⠀⣀⢈⠙⢦⣠⣀⣸⠍⣀⡀⠀⠀⠀⢹⣧⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⢿⣿⣿⣿⣶⣄",
			"⣿⣿⣿⡀⢀⠀⠀⠀⠀⠀⢂⠈⣽⣾⣶⣄⠀⠈⠚⢴⣮⣽⣿⣇⣼⣯⡁⢄⣰⣖⡬⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢷⣸⣽⣿⣿⡏⢿",
			"⣿⣿⣿⡇⢸⠀⠀⠀⠀⠀⠸⣦⠟⣿⣯⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣧⣈⣻⣿⣷⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣏⣿⠹⣿⡇⠘",
			"⣿⣿⣿⡇⠈⠆⠀⠀⠀⠀⠀⡿⠟⠉⠉⠀⠀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⣷⠀⠀⠀⣿⢹⣸⡟⡇⠀",
			"⣿⣿⣿⠇⠠⠀⠀⠀⠀⠀⠀⠀⣴⣴⠀⠀⠀⣶⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⣾⠀⠀⠀⠀⠀⡆⣿⡆⠀⠀⠀⠐⠏⠀⠁⠀",
			"⣿⣿⣿⡆⠀⣷⡀⠀⠀⠀⠀⢄⠻⣿⣤⠘⢾⢿⣧⣿⣿⣿⣿⣿⡟⠛⠛⢿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⢿⢰⣿⠀⠐⠀⠀⢀⠀⡄⠀",
			"⣿⣿⣿⡇⠀⢸⠀⠀⠀⠀⠀⢻⢽⢿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠁⠀⠀⠀⠈⣿⣿⣿⣿⣿⢿⠀⠀⠀⠀⠀⠘⣯⠑⠀⠀⠀⡇⡆⣸⣿⠀",
			"⣿⣿⣿⢣⡐⢸⠀⠀⠀⠀⠀⢱⠈⠀⠻⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⣸⡿⣿⠟⠋⡀⠀⠀⠀⠀⠢⠀⠈⢢⠀⢴⣿⣿⣿⣿⣿⣸",
			"⣿⣿⡇⡼⣷⡄⠀⠀⠀⠀⠀⠈⣷⠀⠀⠙⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣤⣼⣿⠀⠀⠀⠉⠂⠀⠀⠀⠀⠀⠀⠀⠀⢠⠩⢽⣿⣿⣿⣿⣽",
			"⣿⡿⣹⣿⣿⡇⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠈⠛⠛⠛⠛⠻⠿⠿⠿⠿⢫⣴⡾⡇⠀⢠⠀⠀⠀⢠⠀⠀⠀⠀⠀⡏⠀⠀⠀⠈⢩⣿⣿",
			"⣿⣿⣿⣯⣿⡇⠀⠀⠀⠀⣇⠀⠃⡇⢠⠀⠀⠤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⣠⠃⠀⠀⠀⠀⠀⠀⢀⣠⣤⣴⣽⣿⣿",
			"⣿⣟⣿⣿⣿⣇⠀⠆⠀⠀⣿⡀⢸⡧⠟⢂⣤⣶⣷⣶⣄⣀⡀⡀⠀⠀⠀⠀⣭⣴⠸⠀⠀⠀⡰⠁⠀⠀⠀⠀⢀⣤⣶⠿⠿⡽⠾⠟⠋⠻",
			"⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⢸⠟⢈⢠⣶⣯⣿⣿⣿⡿⠟⣩⣾⣷⣆⢀⣠⣴⠿⣣⠀⠀⠀⠀⠀⠀⠀⣀⣴⣶⡿⢡⠁⠀⠀⠁⠀⠀⠀⠀",
			"⣿⣿⣿⣿⣿⣿⣿⣀⠀⣷⣀⣤⣈⣝⢿⣿⣿⣿⣿⣿⣿⡿⡿⢓⢁⣑⢯⡽⡾⢿⠀⠀⠀⠀⢀⣴⣶⣿⣿⡿⠁⠠⠀⠀⠀⠄⠀⠀⠀⠀",
        },
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },
	header_2 = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Quote",
        margin = 5,
        content = {
			"Talk is cheap. Show me the code.",
			"",
			"- Linus Torvalds"
		},
        highlight = "Constant",
        default_color = "",
        oldfiles_amount = 0,
    },
    body = {
        type = "oldfiles",
        oldfiles_directory = false,
        align = "left",
        fold_section = false,
        title = "Oldfiles",
        margin = 5,
        content = "",
        highlight = "String",
        default_color = "",
        oldfiles_amount = 5,
    },
    body_2 = {
        type = "oldfiles",
        oldfiles_directory = true,
        align = "left",
        fold_section = false,
        title = "",
        margin = 5,
        content = "",
        highlight = "String",
        oldfiles_amount = 5,
    },
    options = {
        after = function()
            require("startup.utils").oldfiles_mappings()
        end,
        mapping_keys = false,
        cursor_column = 0.25,
        empty_line_between_mappings = false,
        disable_statuslines = true,
        paddings = { 1, 1, 1, 1 },
    },
    mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "header_2", "body", "body_2" },
})
